sample/codepkg/objects/Account_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Qualifications</relationshipLabel>
        <relationshipName>Account_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_the_section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check the section</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Qualification</label>
    <nameField>
        <label>Account Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/codepkg/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_the_section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check the section</label>
        <type>Checkbox</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/codepkg/classes/multirecordtest.cls
@istest
Public class multirecordtest
{
public static testmethod void multirecords()
{
try{
Account ac=new account();
ac.Name='venki';
ac.Check__c=false;
insert ac;

Contact con=new contact();
con.lastname='venki';
con.accountid=ac.id;
insert con;
Deal__c d=new Deal__c();
d.Check_the_section__c=true;
d.Account__c=ac.id;
insert d;
Account_Qualification__c aq=new Account_Qualification__c();
aq.Check_the_section__c=true;
aq.Account__c=ac.id;
insert aq;

Task t =new Task(Status='In Progress',WhoId = Con.id,WhatId = d.Id,ActivityDate=System.Today());
multirecords m=new multirecords();
m.save();
Account ac1=new account();
ac1.Name='venki';
ac1.Check__c=false;
insert ac1;
Contact con1=new contact();
con1.lastname='venki';
con1.accountid=ac1.id;
insert con1;
}catch(Exception e){system.debug('!!!!'+e);}
}

}