sample/codepkg/objects/Account_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Qualifications</relationshipLabel>
        <relationshipName>Account_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_the_section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check the section</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Qualification</label>
    <nameField>
        <label>Account Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/codepkg/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_the_section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check the section</label>
        <type>Checkbox</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/codepkg/classes/multirecords.cls
public class multirecords {

public Account A {get; set;}
Public Contact C {get; set;}
Public Deal__c O {get; set;}
Public Account_Qualification__c AQ{get;set;}
public Task t{get;set;}
public multirecords()
{
A = new account();
C = new contact();
O = new Deal__c();
AQ = new Account_Qualification__c();
t = new Task();
}

public PageReference Save()
{
insert A;

C.Accountid = A.id;


AQ.Account__c=A.Id;
if(A.Check__c== true)
{
insert AQ;
}
O.Account__c = A.id;

If (O.name != NULL || C.lastname != NULL || AQ.Check_the_section__c == true )
{
insert O;
insert C;
}
if(O.Check_the_section__c == true)
{
t.WhoId=C.id;
t.WhatId=O.id;
insert t;
}
return new PageReference('/'+A.id);
}
}